name: WireGuard Client
slug: wireguard_client
description: "Simple WireGuard client that connects Home Assistant to a remote WireGuard server."
version: "0.0.1"
stage: experimental

arch:
  - amd64
  - aarch64

startup: services
boot: auto

# HA soll das Image aus dem Dockerfile lokal bauen
image: "local/ha-wireguard-client-{arch}"

# Welche Ordner in HA der Container sehen darf (erstmal konservativ)
map:
  - ssl:rw
  - config:rw
  - share:rw

options:
  enabled: false
  config_file: /ssl/wireguard/client.conf

schema:
  enabled: bool
  config_file: str
