name: WireGuard Client
slug: wireguard_client
version: 0.0.9
description: Simple WireGuard client that connects Home Assistant to a remote WireGuard server.
arch:
  - amd64
  - aarch64
  - armv7

startup: services
init: false
host_network: true

privileged:
  - NET_ADMIN
  - SYS_MODULE

devices:
  - /dev/net/tun

options:
  private_key: ""
  address: ""
  dns: ""
  public_key: ""
  preshared_key: ""
  endpoint: ""
  allowed_ips: ""
  config_content: ""

schema:
  private_key: password
  address: str
  dns: str?
  public_key: str
  preshared_key: password?
  endpoint: str
  allowed_ips: str?
