name: "WireGuard Client"
version: "0.0.1"
slug: "wireguard_client"
description: "Simple WireGuard client that connects Home Assistant to a remote WireGuard server."
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false

# Wir brauchen Network-Privilegien f√ºr WireGuard
privileged:
  - NET_ADMIN
  - SYS_MODULE

# /ssl wird gemountet, falls du weiterhin mit Dateipfad arbeiten willst
map:
  - ssl:rw

options:
  enabled: false
  config_file: "/ssl/wireguard/client.conf"
  config_content: ""

schema:
  enabled: bool
  config_file: str
  config_content: str
