name: WireGuard Client
slug: wireguard_client
description: "Simple WireGuard client that connects Home Assistant to a remote WireGuard server."
version: "0.0.1"
stage: experimental

arch:
  - amd64
  - aarch64

startup: services
boot: auto

# WICHTIG: KEIN 'image:' MEHR â†’ dann baut HA aus dem Dockerfile

options:
  enabled: false
  config_file: /ssl/wireguard/client.conf

schema:
  enabled: bool
  config_file: str
